Added deploy with vault

diff --git a/.github/workflows/good_cicd.yaml b/.github/workflows/good_cicd.yaml
--- a/.github/workflows/good_cicd.yaml
+++ b/.github/workflows/good_cicd.yaml
@@ -61,11 +61,15 @@ jobs:
           cache-dependency-path: hw4_cicd/go.mod
       - name: Generate Coverage Report
         run: go test -v -coverprofile=coverage.out ./...
+      - name: Convert Profile to HTML
+        run: go tool cover -html=coverage.out -o coverage.html
       - name: Upload Coverage Artifact
         uses: actions/upload-artifact@v7
         with:
           name: code-coverage
-          path: hw4_cicd/coverage.out
+          path: |
+            hw4_cicd/coverage.out
+            hw4_cicd/coverage.html
 
   build:
     name: Build
@@ -84,7 +88,7 @@ jobs:
       - name: Build Binary
         run: go build -ldflags="-s -w" -v -o app ./cmd/main.go
       - name: Upload Binary Artifact
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         with:
           name: app-binary
           path: hw4_cicd/app
@@ -104,4 +108,49 @@ jobs:
           cache: true
           cache-dependency-path: hw4_cicd/go.mod
       - name: Run Govulncheck
-        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...
+        run: |
+          go install golang.org/x/vuln/cmd/govulncheck@v1
+          govulncheck ./...
+
+  deploy:
+    name: Deploy
+    needs: security
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    runs-on: ubuntu-24.04
+    environment: test_prod
+    defaults:
+      run:
+        working-directory: ./hw4_cicd
+    steps:
+      - uses: actions/checkout@v6
+      - name: Download Binary from Build Stage
+        uses: actions/download-artifact@v8
+        with:
+          name: app-binary
+          path: ./hw4_cicd
+      - name: Import Secrets from Vault
+        uses: hashicorp/vault-action@v3
+        with:
+          url: ${{ secrets.VAULT_URL }}
+          token: ${{ secrets.VAULT_TOKEN }}
+          secrets: |
+            secret/data/hw4_cicd TEST_TOKEN
+      - name: Verify Vault Secret
+        run: |
+          if [ -z "$TEST_TOKEN" ]; then
+            echo "Error: TEST_TOKEN is empty"
+            exit 1
+          else
+            echo "Success: TEST_TOKEN is $TEST_TOKEN"
+          fi
+      - name: Run App
+        run: |
+          chmod +x ./app
+          RESULT=$(echo "RaceCar" | ./app)
+
+          if [ "$RESULT" == "True" ]; then
+            echo "Success: Palindrome detected!"
+          else
+            echo "Failure: Expected palindrome!"
+            exit 1
+          fi
